version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    networks:
      - culturemoa-network
    ports:
      - "8101:8100"
    volumes:
      - app_data:/app/data   # 앱 데이터용 볼륨 (필요시 수정)

volumes:
  app_data:

networks:
  culturemoa-network:
    external: true