-- 카테고리 존재하지 않을 경우만 INSERT
INSERT INTO CATEGORY_TBL (name, sdate)
SELECT '상품', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORY_TBL WHERE name = '상품');
INSERT INTO CATEGORY_TBL (name, sdate)
SELECT '상품장르', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORY_TBL WHERE name = '상품장르');
INSERT INTO CATEGORY_TBL (name, sdate)
SELECT '티켓', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORY_TBL WHERE name = '티켓');
INSERT INTO CATEGORY_TBL (name, sdate)
SELECT '게시판', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORY_TBL WHERE name = '게시판');
INSERT INTO CATEGORY_TBL (name, sdate)
SELECT '거래평가', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORY_TBL WHERE name = '거래평가');
INSERT INTO CATEGORY_TBL (name, sdate)
SELECT '결제', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORY_TBL WHERE name = '결제');

-- 상품 카테고리 (parent_idx = 1, '상품')
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 1001, 1, '포토카드', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 1001);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 1002, 1, '음반, 영상', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 1002);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 1003, 1, '화보', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 1003);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 1004, 1, '인형', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 1004);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 1005, 1, '응원도구', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 1005);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 1006, 1, '의류', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 1006);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 1007, 1, '기타', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 1007);

-- 상품장르 카테고리 (parent_idx = 2, '상품장르')
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 2001, 2, '가수', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 2001);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 2002, 2, '배우', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 2002);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 2003, 2, '스포츠', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 2003);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 2004, 2, '애니', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 2004);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 2005, 2, '기타', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 2005);

-- 티켓 카테고리 (parent_idx = 3, '티켓')
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3001, 3, '콘서트', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3001);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3002, 3, '뮤지컬', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3002);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3003, 3, '연극', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3003);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3004, 3, '전시', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3004);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3005, 3, '클래식', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3005);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3006, 3, '아동/가족', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3006);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3007, 3, '레저', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3007);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 3008, 3, '스포츠', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 3008);

-- 게시판 카테고리 (parent_idx = 4, '게시판')
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 4001, 4, '잡담', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 4001);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 4002, 4, '삽니다', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 4002);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 4003, 4, '팝니다', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 4003);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 4004, 4, '기타', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 4004);

-- 거래평가 카테고리 (parent_idx = 5, '거래평가')
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5001, 5, '답변이 빨라요.', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5001);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5002, 5, '친절해요.', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5002);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5003, 5, '물건이 깨끗해요.', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5003);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5004, 5, '가성비에요.', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5004);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5005, 5, '약속 시간을 잘 지켜요.', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5005);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5006, 5, '상품 설명이 부족해요.', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5006);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5007, 5, '이미지와 상품이 달라요.', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5007);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5008, 5, '늦은 시간에 연락해요', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5008);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5009, 5, '불친절해요', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5009);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 5010, 5, '사기당했어요!', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 5010);

-- 결제 카테고리 (parent_idx = 6, '결제')
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 6001, 6, '카카오페이', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 6001);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 6002, 6, '토스페이', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 6002);
INSERT INTO CATEGORYSUB_TBL (sub_idx, parent_idx, name, sdate)
SELECT 6003, 6, '네이버페이', SYSDATE() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CATEGORYSUB_TBL WHERE sub_idx = 6003);