-- 유저 테이블
CREATE TABLE IF NOT EXISTS USER_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    ID varchar(50) NOT NULL UNIQUE,
	NAME varchar(50) NOT NULL,
	EMAIL varchar(50) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	ADDRESS varchar(255) NOT NULL,
	NICKNAME varchar(50) NOT NULL,
    SOCIAL_LOGIN varchar(50) NOT NULL,
	SDATE date NOT NULL,
	CDATE date,
	EDATE date
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 카테고리 테이블
CREATE TABLE IF NOT EXISTS CATEGORY_TBL (
  IDX int NOT NULL AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  SDATE date NOT NULL,
  EDATE date DEFAULT NULL,
  PRIMARY KEY (IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 카테고리 서브 테이블
CREATE TABLE IF NOT EXISTS CATEGORYSUB_TBL (
  IDX int NOT NULL AUTO_INCREMENT,
  SUB_IDX int NOT NULL,
  PARENT_IDX int NOT NULL,
  NAME varchar(50) NOT NULL,
  SDATE date NOT NULL,
  EDATE date DEFAULT NULL,
  PRIMARY KEY (IDX),
  UNIQUE KEY SUB_IDX_UNIQUE (SUB_IDX),
  KEY CATEGORYSUB_FK (PARENT_IDX),
  CONSTRAINT CATEGORYSUB_FK FOREIGN KEY (PARENT_IDX) REFERENCES CATEGORY_TBL (IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;


-- 상품 테이블
CREATE TABLE IF NOT EXISTS PRODUCT_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_IDX int NOT NULL,
	CATEGORYGENRE_IDX int NOT NULL,
    TITLE varchar(255) NOT NULL,
	SDATE date NOT NULL,
	EDATE date ,
	USER_IDX int NOT NULL,
	PRICE DECIMAL NOT NULL,
	FLAG BOOLEAN NOT NULL,
	CONTENT TEXT NOT NULL,
  CONSTRAINT PRODUCT_FK1 FOREIGN KEY(CATEGORY_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX),
  CONSTRAINT PRODUCT_FK2 FOREIGN KEY(CATEGORYGENRE_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX),
  CONSTRAINT PRODUCT_FK3 FOREIGN KEY (USER_IDX) REFERENCES USER_TBL(IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 상품 이미지 테이블
CREATE TABLE IF NOT EXISTS PRODUCT_IMAGE_TBL (
  IDX       INT AUTO_INCREMENT,
  PRODUCT_IDX INT NOT NULL,
  IMAGE_URL TEXT NOT NULL,
  FLAG TINYINT,
  PRIMARY KEY (IDX),
  CONSTRAINT PRODUCT_IMAGE_FK FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT_TBL(IDX)
  );

-- 유저 거래내역 테이블
CREATE TABLE IF NOT EXISTS USER_TRANSACTION_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    PRODUCT_IDX int NOT NULL,
	SDATE date NOT NULL,
    CONSTRAINT USER_TRANSACTION_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_TRANSACTION_FK2 FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT_TBL(IDX),
    CONSTRAINT USER_TRANSACTION_UQ UNIQUE (USER_IDX, PRODUCT_IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 유저리뷰 테이블
CREATE TABLE IF NOT EXISTS USER_REVIEW_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    WRITER_USER_IDX int NOT NULL,   -- 남기는 사람
    RECEIVER_USER_IDX int NOT NULL, -- 보는 사람
    TRANSACTION_IDX int NOT NULL,
    RATING FLOAT not NULL,
    REVIEW varchar(255),
    SDATE date NOT NULL,
    CDATE date,
    CONSTRAINT USER_REVIEW_FK1 FOREIGN KEY(WRITER_USER_IDX ) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_REVIEW_FK2 FOREIGN KEY(RECEIVER_USER_IDX ) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_REVIEW_FK3 FOREIGN KEY(TRANSACTION_IDX) REFERENCES USER_TRANSACTION_TBL(IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 유저 거래 평가 테이블
CREATE TABLE IF NOT EXISTS USER_REVIEW_EVALUATION_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL UNIQUE, -- 유저 고유 번호
    EVAL_5001 int DEFAULT 0, -- 답변이 빨라요.
    EVAL_5002 int DEFAULT 0, -- 친절해요.
    EVAL_5003 int DEFAULT 0, -- 물건이 깨끗해요.
    EVAL_5004 int DEFAULT 0, -- 가성비에요.
    EVAL_5005 int DEFAULT 0, -- 약속 시간을 잘 지켜요.
    EVAL_5006 int DEFAULT 0, -- 상품 설명이 부족해요.
    EVAL_5007 int DEFAULT 0, -- 이미지와 상품이 달라요.
    EVAL_5008 int DEFAULT 0, -- 늦은 시간에 연락해요.
    EVAL_5009 int DEFAULT 0, -- 불친절해요.
    EVAL_5010 int DEFAULT 0, -- 사기당했어요.
    CONSTRAINT USER_REVIEW_EVALUATION_FK1 FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 리뷰별 평가 항목 기록 테이블
CREATE TABLE IF NOT EXISTS USER_REVIEW_EVALUATION_RECORD_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    REVIEW_IDX int NOT NULL UNIQUE,
    EVAL_5001 TINYINT DEFAULT 0, -- 답변이 빨라요.
    EVAL_5002 TINYINT DEFAULT 0, -- 친절해요.
    EVAL_5003 TINYINT DEFAULT 0, -- 물건이 깨끗해요.
    EVAL_5004 TINYINT DEFAULT 0, -- 가성비에요.
    EVAL_5005 TINYINT DEFAULT 0, -- 약속 시간을 잘 지켜요.
    EVAL_5006 TINYINT DEFAULT 0, -- 상품 설명이 부족해요.
    EVAL_5007 TINYINT DEFAULT 0, -- 이미지와 상품이 달라요.
    EVAL_5008 TINYINT DEFAULT 0, -- 늦은 시간에 연락해요.
    EVAL_5009 TINYINT DEFAULT 0, -- 불친절해요.
    EVAL_5010 TINYINT DEFAULT 0, -- 사기당했어요.
    CONSTRAINT USER_REVIEW_EVALUATION_RECORD_FK1 FOREIGN KEY(REVIEW_IDX) REFERENCES USER_REVIEW_TBL(IDX)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 유저 선호도 테이블
CREATE TABLE IF NOT EXISTS USER_FAVORITE_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL UNIQUE,
    FAV_1001 TINYINT DEFAULT 0,  -- 포토카드
    FAV_1002 TINYINT DEFAULT 0,  -- 음반, 영상
    FAV_1003 TINYINT DEFAULT 0,  -- 화보
    FAV_1004 TINYINT DEFAULT 0,  -- 인형
    FAV_1005 TINYINT DEFAULT 0,  -- 응원도구
    FAV_1006 TINYINT DEFAULT 0,  -- 의류
    FAV_1007 TINYINT DEFAULT 0,  -- 기타
    FAV_2001 TINYINT DEFAULT 0,  -- 가수(상품)
    FAV_2002 TINYINT DEFAULT 0,  -- 배우
    FAV_2003 TINYINT DEFAULT 0,  -- 스포츠
    FAV_2004 TINYINT DEFAULT 0,  -- 애니
    FAV_2005 TINYINT DEFAULT 0,  -- 기타(장르)
    FAV_3001 TINYINT DEFAULT 0,  -- 콘서트
    FAV_3002 TINYINT DEFAULT 0,  -- 뮤지컬
    FAV_3003 TINYINT DEFAULT 0,  -- 연극
    FAV_3004 TINYINT DEFAULT 0,  -- 전시
    FAV_3005 TINYINT DEFAULT 0,  -- 클래식
    FAV_3006 TINYINT DEFAULT 0,  -- 아동/가족
    FAV_3007 TINYINT DEFAULT 0,  -- 레저
    FAV_3008 TINYINT DEFAULT 0,  -- 스포츠
    CONSTRAINT USER_FAVORITE_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 유저 찜 테이블
CREATE TABLE IF NOT EXISTS USER_PICK_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    PRODUCT_IDX int NOT NULL,
	SDATE date NOT NULL,
	EDATE date,
    CONSTRAINT USER_PICK_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_PICK_FK2 FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT_TBL(IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;



-- 게시판 테이블
CREATE TABLE IF NOT EXISTS CONTENTS_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    CATEGORY_IDX int NOT NULL,
	TITLE varchar(50) NOT NULL,
	CONTENT TEXT NOT NULL,
	SDATE date NOT NULL,
	CDATE date,
	EDATE date,
    CONSTRAINT CONTENTS_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT CONTENTS_FK2 FOREIGN KEY(CATEGORY_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 게시판 댓글 테이블
CREATE TABLE IF NOT EXISTS CONTENTS_COMMENT_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    CONTENTS_IDX int NOT NULL,
	TEXT varchar(255) NOT NULL,
	SDATE date NOT NULL,
	CDATE date,
	EDATE date,
    CONSTRAINT CONTENTS_COMMENT_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT CONTENTS_COMMENT_FK2 FOREIGN KEY(CONTENTS_IDX) REFERENCES CONTENTS_TBL(IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 게시판 이미지 등록 테이블
CREATE TABLE IF NOT EXISTS CONTENTS_DETAIL_IMAGE_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    CONTENTS_IDX int NOT NULL,
    IMAGE_URL TEXT NOT NULL,
    CONSTRAINT CONTENTS_DETAIL_IMAGE_FK FOREIGN KEY(CONTENTS_IDX) REFERENCES CONTENTS_TBL(IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 티켓 테이블
CREATE TABLE IF NOT EXISTS TICKET_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    SUB_IDX int NOT NULL,
	TITLE varchar(255) NOT NULL,
	COMPANY varchar(50) NOT NULL,
    LINK text NOT NULL,
	SDATE date NOT NULL,
	EDATE date NOT NULL,
	PLACE varchar(255) NOT NULL,
	PRICE varchar(255),
	GRADE varchar(50),
	CAST varchar(255),
	RUNNINGTIME varchar(50),
    IMG text,
    ETC text,
    CONSTRAINT TICKET_FK FOREIGN KEY(SUB_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 결제기록 테이블
CREATE TABLE IF NOT EXISTS PAYMENT_HISTORY_TBL
(
    IDX int AUTO_INCREMENT PRIMARY KEY,
	TID varchar(50) NOT NULL UNIQUE,
	AMOUNT int NOT NULL,
	PAY_METHOD int NOT NULL,
	BUYER_IDX int NOT NULL,
    SELLER_IDX int NOT NULL,
	PRODUCT_IDX int NOT NULL,
	TRADE_TYPE int NOT NULL,
	DELIVERY_ADDRESS varchar(255),
	CONSTRAINT PAYMENT_HISTORY_FK1 FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT_TBL (IDX),
    CONSTRAINT PAYMENT_HISTORY_FK2 FOREIGN KEY(BUYER_IDX) REFERENCES USER_TBL (IDX),
	CONSTRAINT PAYMENT_HISTORY_FK3 FOREIGN KEY(SELLER_IDX) REFERENCES USER_TBL (IDX),
	CONSTRAINT PAYMENT_HISTORY_FK4 FOREIGN KEY(PAY_METHOD) REFERENCES CATEGORYSUB_TBL(SUB_IDX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 결제상태 테이블
CREATE TABLE IF NOT EXISTS PAYMENT_STATUS_TBL
(
    IDX int AUTO_INCREMENT PRIMARY KEY,
	TID varchar(50) NOT NULL,
	CREATED_AT timestamp null,	-- 결제준비, 결제승인, 결제취소, 결제실패
    APPROVED_AT timestamp null,
    CANCELED_AT timestamp null,
    FAILED_AT timestamp null,
    CONSTRAINT PAYMENT_STATUS_TBL FOREIGN KEY(TID) REFERENCES PAYMENT_HISTORY_TBL (TID)
)  CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;


