-- 유저 테이블
CREATE TABLE IF NOT EXISTS USER_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    ID varchar(50) NOT NULL UNIQUE,
	NAME varchar(50) NOT NULL,
	EMAIL varchar(50) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	ADDRESS varchar(255) NOT NULL,
	NICKNAME varchar(50) NOT NULL,
    SOCIAL_LOGIN varchar(50) NOT NULL,
	SDATE date NOT NULL,
	CDATE date,
	EDATE date
);

-- 카테고리 테이블
CREATE TABLE IF NOT EXISTS CATEGORY_TBL (
  IDX int NOT NULL AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  SDATE date NOT NULL,
  EDATE date DEFAULT NULL,
  PRIMARY KEY (IDX)
);

-- 카테고리 서브 테이블
CREATE TABLE IF NOT EXISTS CATEGORYSUB_TBL (
  IDX int NOT NULL AUTO_INCREMENT,
  SUB_IDX int NOT NULL,
  PARENT_IDX int NOT NULL,
  NAME varchar(50) NOT NULL,
  SDATE date NOT NULL,
  EDATE date DEFAULT NULL,
  PRIMARY KEY (IDX),
  UNIQUE KEY SUB_IDX_UNIQUE (SUB_IDX),
  KEY CATEGORYSUB_FK (PARENT_IDX),
  CONSTRAINT CATEGORYSUB_FK FOREIGN KEY (PARENT_IDX) REFERENCES CATEGORY_TBL (IDX)
);


-- 상품 테이블
CREATE TABLE IF NOT EXISTS PRODUCT_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_IDX int NOT NULL,
	CATEGORYGENRE_IDX int NOT NULL,
    TITLE varchar(255) NOT NULL,
	SDATE date NOT NULL,
	EDATE date ,
	USERID varchar(50) NOT NULL,
	PRICE DECIMAL NOT NULL,
	FLAG BOOLEAN NOT NULL,
  CONSTRAINT PRODUCT_FK1 FOREIGN KEY(CATEGORY_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX),
  CONSTRAINT PRODUCT_FK2 FOREIGN KEY(CATEGORYGENRE_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX)
);

-- 유저 거래내역 테이블
CREATE TABLE IF NOT EXISTS USER_TRANSACTION_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    PRODUCT_IDX int NOT NULL,
	  CATEGORYSUB_IDX int NOT NULL,
	  SDATE date NOT NULL,
    CONSTRAINT USER_TRANSACTION_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_TRANSACTION_FK2 FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT_TBL(IDX),
    CONSTRAINT USER_TRANSACTION_FK3 FOREIGN KEY(CATEGORYSUB_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX)
);

-- 유저리뷰 테이블
CREATE TABLE IF NOT EXISTS USER_REVIEW_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    TRANSACTION_IDX int NOT NULL,
    RATING FLOAT not NULL,
    REVIEW varchar(255),
    SDATE date NOT NULL,
    CDATE date,
    CONSTRAINT USER_REVIEW_FK1 FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_REVIEW_FK2 FOREIGN KEY(TRANSACTION_IDX) REFERENCES USER_TRANSACTION_TBL(IDX)
);

-- 유저 거래 평가 테이블
CREATE TABLE IF NOT EXISTS USER_REVIEW_EVALUATION_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    REVIEW_IDX int NOT NULL,
    CATEGORYSUB_IDX int NOT NULL,
    IS_EVALUATION TINYINT NOT NULL,
    SDATE date NOT NULL,
    CDATE date,
    CONSTRAINT USER_REVIEW_EVALUATION_FK1 FOREIGN KEY(REVIEW_IDX) REFERENCES USER_REVIEW_TBL(IDX),
    CONSTRAINT USER_REVIEW_EVALUATION_FK2 FOREIGN KEY(CATEGORYSUB_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX),
    CONSTRAINT UC_REVIEW_EVAL UNIQUE (REVIEW_IDX, CATEGORYSUB_IDX)
);

-- 유저 선호도 테이블
CREATE TABLE IF NOT EXISTS USER_FAVORITE_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    CATEGORYSUB_IDX int NOT NULL,
    SDATE    DATE NOT NULL,
    IS_FAVORITE TINYINT NOT NULL,
    CDATE date,
    CONSTRAINT USER_FAVORITE_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_FAVORITE_FK2 FOREIGN KEY(CATEGORYSUB_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX),
    CONSTRAINT UC_USER_FAVORITE UNIQUE (USER_IDX, CATEGORYSUB_IDX)
);

-- 유저 찜 테이블
CREATE TABLE IF NOT EXISTS USER_PICK_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    PRODUCT_IDX int NOT NULL,
	SDATE date NOT NULL,
	FLAG BOOLEAN NOT NULL,
	CDATE date,
    CONSTRAINT USER_PICK_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT USER_PICK_FK2 FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT_TBL(IDX)
);

-- 상품 상세 테이블
CREATE TABLE IF NOT EXISTS PRODUCT_DETAIL_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_IDX int NOT NULL,
    CONTENT TEXT NOT NULL,
	IMAGE_URL TEXT NOT NULL,
    CONSTRAINT PRODUCT_DETAIL_FK FOREIGN KEY(PRODUCT_IDX) REFERENCES PRODUCT_TBL(IDX)
);

-- 게시판 테이블
CREATE TABLE IF NOT EXISTS CONTENTS_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    CATEGORY_IDX int NOT NULL,
	TITLE varchar(50) NOT NULL,
	DIVISION int NOT NULL,
	CONTENT TEXT NOT NULL,
	SDATE date NOT NULL,
	EDATE date,
    CONSTRAINT CONTENTS_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT CONTENTS_FK2 FOREIGN KEY(CATEGORY_IDX) REFERENCES CATEGORY_TBL(IDX)
);

-- 게시판 댓글 테이블
CREATE TABLE IF NOT EXISTS CONTENTS_COMMENT_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    USER_IDX int NOT NULL,
    CONTENTS_IDX int NOT NULL,
	TEXT varchar(255) NOT NULL,
	SDATE date NOT NULL,
    CONSTRAINT CONTENTS_COMMENT_FK FOREIGN KEY(USER_IDX) REFERENCES USER_TBL(IDX),
    CONSTRAINT CONTENTS_COMMENT_FK2 FOREIGN KEY(CONTENTS_IDX) REFERENCES CONTENTS_TBL(IDX)
);

-- 티켓 테이블
CREATE TABLE IF NOT EXISTS TICKET_TBL
(
    IDX       int AUTO_INCREMENT PRIMARY KEY,
    SUB_IDX int NOT NULL,
	TITLE varchar(255) NOT NULL,
	COMPANY varchar(50) NOT NULL,
    LINK text NOT NULL,
	SDATE date NOT NULL,
	EDATE date NOT NULL,
	PLACE varchar(255) NOT NULL,
	PRICE varchar(255) NOT NULL,
	GRADE varchar(50),
	CAST varchar(255),
	RUNNINGTIME varchar(50),
    IMG text,
    ETC text,
    CONSTRAINT TICKET_FK FOREIGN KEY(SUB_IDX) REFERENCES CATEGORYSUB_TBL(SUB_IDX)
);

-- 결제기록 테이블
CREATE TABLE IF NOT EXISTS PAYMENT_HISTORY_TBL
(
    IDX int AUTO_INCREMENT PRIMARY KEY,
	TID varchar(50) NOT NULL UNIQUE,
	AMOUNT int NOT NULL,
	PAY_METHOD varchar(20) NOT NULL,
	BUYER_IDX int NOT NULL,
    SELLER_IDX int NOT NULL,
	PRODUCT_IDX int NOT NULL,
	TRADE_TYPE varchar(20),		-- 수령 방법
	DELIVERY_ADDRESS varchar(255),
	foreign key(PRODUCT_IDX) references PRODUCT_TBL (IDX),
    foreign key(BUYER_IDX) references USER_TBL (IDX),
	foreign key(SELLER_IDX) references USER_TBL (IDX)
);

-- 결제상태 테이블
CREATE TABLE IF NOT EXISTS PAYMENT_STATUS_TBL
(
	TID varchar(50) NOT NULL,
	STATUS varchar(50) NOT NULL,	-- 결제준비, 결제승인, 결제취소, 결제실패
    STATUS_AT date NOT NULL		-- createdAt, approvedAt, canceledAt
);

